personal_information = [
    ("l'uomo", "der Mann"),
    ("i uomini", "die Männer"),
    ("la donna", "die Frau"),
    ("il signor", "der Herr"),
    ("la signora", "die Frau"),
    ("la signorina", "die junge Frau"),
    ("il bebè", "das Baby"),
    ("il bambini", "der Junge / das Kind"),
    ("la bambina", "das Mädchen / das Kind"),
    ("il ragazzo", "der Junge"), # issue with Deu -> Ital ambiguous
    ("la ragazza", "das Mädchen"),
    ("chiamare", "nennen"),
    ("chimarsi", "heißen"),
    ("il nome", "der Vorname / der Name"),
    ("il cognome", "der Nachname"),
    ("sposato / sposata", "verheiratet"),
    ("celibe / nubile", "ledig / single"), # celibe only for males, nubile only for femals - how do I handle that?
    ("divorziato / divorziata", "geschieden"),
    ("vedovo / vedova", "verwitwet"),
    ("essere separato / essere separata", "gertennt leben"),
    ("venire da", "kommen aus"),
    ("essere di", "sein aus"),
    ("l'indirizzo", "die Adresse"),
    ("la città", "der Wohnort"), # how do distinguish this from "die Stadt"
    ("la via", "die Straße"),
    ("il numero (civico)", "die Hausnummer"),
    ("il numero di telefono", "die Telefonnummer"),
    ("il numero di cellulare", "die Handynummer"),
    ("maggiorenne", "volljährig"),
    ("minorenne", "minderjährig")
    ]

character_traits = [
    ("buono / buona", "gut / lieb"), # git Person
    ("bravo / brava", "gut / brav"), # gut Fähigkeit
    ("cattivo / cattiva", "schlecht"),
    ("gentile", "freundlich / nett / aufmerksam"),
    ("cordiale", "herzlich"),
    ("cortese", "höflich"),
    ("sgarbato / sgarbata", "unhöflich"),
    ("la pazienza", "die Geduld"),
    ("paziente", "geduldig"),
    ("impaziente", "ungeduldig"),
    ("prudente", "vorsichtig"),
    ("imprudente", "unvorsichtig"),
    ("serio / seria", "ernsthaft / ernst"),
    ("simpatico / simpatica", "sympatisch / nett"),
    ("antipatico / antipatica", "unsympathisch"),
    ("pigro / pigra", "faul"),
    ("allegro / allegra", "fröhlich / heiter / lustig"),
    ("comico / comica", "komisch"),
    ("depresso / depressa", "niedergeschlagen"),
    ("calmo / calma", "ruhig"),
    ("furbo / furba", "schlau"),
    ("la stupidità", "die Dummheit"),
    ("stupido / stupida", "dumm"),
    ("il coraggio", "der Mut"),
    ("coraggioso / coraggiosa", "mutig"),
    ("il vigliacco / la vigliacca", "der Feigling"),
    ("abituato / abituata", "gewöhnlich"),
    ("la personalità", "die Persönlichkeit"),
    ("il carattere", "der Charakter")
    ]

appearance = [
    ("l'aspetto", "das Aussehen"),
    ("sembrare", "aussehen"),
    ("carino / carina", "hübsch"),
    ("la bellezza", "die Schönheit"),
    ("bello / bella", "schön / gut  aussehend"), # wird wie bestimmter Artikel angepasst
    ("attraente", "attraktiv"),
    ("brutto / brutta", "hässlich"),
    ("la faccia", "das Gesicht"),
    ("la linea", "die Figur"),
    ("grande", "groß"), # wird zu gran vor Substantiven mit Vokal
    ("alto / alta", "groß"),
    ("grosso / grossa", "kräftig"),
    ("grasso / grassa", "dick"),
    ("piccolo / piccola / basso / bassa", "klein"), # the last relate only to hight
    ("magro / magra", "dünn"),
    ("minuto / minuta", "zierlich"),
    ("snello / snella", "schlank"),
    ("assomigliare", "ähnlich"),
    ("assomigliarsi", "sich gleichen"),
    ("come", "so wie"),
    ("il capello", "das Haar / das Kopfhaar"),
    ("il pelo", "das Körperhaar"),
    ("la pettinatura", "die Frisur"),
    ("pettinare", "frisieren"),
    ("biondo / bionda", "blond"),
    ("castano / castana", "braunhaarig"),
    ("nero / nera", "schwarz"),
    ("rosso / rossa", "rot"),
    ("grigio / grigia", "grau"),
    ("moro / mora", "dunkelhaarig"), # auch Hautfarbe
    ("chiaro / chiara", "hell"),
    ("scuro / scura", "dunkel")
    ]

clothing = [
    ("l'abbigliamento", "die Kleidung"),
    ("la moda", "die Mode"),
    ("elegante", "elegant"),
    ("vestirsi", "sich anziehen"),
    ("mettersi", "anziehen"),
    ("portare", "tragen / anhaben"),
    ("togliersi", "ausziehen"),
    ("spogliarsi", "sich ausziehen"),
    ("cambiarsi", "such umziehen"),
    ("provare", "anprobieren"),
    ("stare", "stehen / passen"),
    ("il numero", "die Schuhgröße"),
    ("la taglia", "die Kleidergröße"),
    ("stretto / stretta", "eng"),
    ("largo / larga", "weit"),
    ("corto / corta", "kurz"),
    ("lungo / lunga", "lang"),
    ("la giacca", "die Jacke"),
    ("il cappotto", "der Mantel"),
    ("l'impermeabile", "die Regenjacke"),
    ("l'abito", "der Anzug / das Kleid"),
    ("il tailleur", "das Kostüm"),
    ("il vestito", "das Kleid"),
    ("i vestiti", "die Kleidung"),
    ("i pantaloni", "die Hose"),
    ("i pantaloncini", "die Shorts"),
    ("i jeans", "die Jeans"),
    ("la gonna", "der Rock"),
    ("la camicia", "das Hemd"),
    ("la camicetta", "die Bluse"),
    ("la maglia", "der Pullover"),
    ("la maglietta", "das T-Shirt"),
    ("la calza", "der Strumpf"),
    ("il calzino", "die Socke"),
    ("la scarpa", "der Schuh"),
    ("il pigiama", "der Schlafanzug"),
    ("la camicia da notte", "das Nachthemd"),
    ("il costume da bagno", "der Badeanzug / die Badehose"),
    ("le mutande", "der Slip / die Unterhose"),
    ("il bikini", "der Bikini")
    ]

list_vocab_pairs_ital_deu = personal_information + character_traits + appearance + clothing
