list_vocab_pairs_jap_deu = [
    ("すし", "Sushi"),
    ("みず", "Wasser"),
    ("ください", "bitte"),
    ("ごはん", "Reis"),
    ("です", "da ist / es ist / ich bin"),
    ("いしゃ", "Arzt"),
    ("せんせい", "Lehrer"),
    ("やさしい", "einfach / nett"),
    ("べんごし", "Anwalt"),
    ("かっこいい", "cool"),
    ("ひと", "Person"),
    ("がくせい", "Schüler"),
    ("けん", "Ken / Ticket"),
    ("こんにちは", "hallo / hi"),
    ("どうぞよろしく", "schön dich kennenzulernen"),
    ("はな", "Blume"),
    ("なおみ", "Naomi"),
    ("さん", "Herr / Frau"),
    ("こんばんは", "guten Abend / heute Abend"),
    ("はい", "ja"),
    ("いいえ", "nein"),
    ("にほん", "Japan"),
    ("にほんじん", "Japaner"),
    ("カナダ", "Kanada"),
    ("カナダじん", "Kanadier"),
    ("メリカ", "Amerika"),
    ("アメリカじん", "Amerikaner"),
    ]
